name: forestring_teacher_2
description: "포레스트링 선생님"
publish_to: 'none'

version: 3.2.2+61

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.1.2
  shared_preferences: ^2.2.1
  connectivity_plus: ^7.0.0
  flutter_native_splash: ^2.4.1
  syncfusion_flutter_calendar: ^34.2.5
  flutter_colorpicker: ^1.1.0
  ntp: ^2.0.0
  provider: ^6.0.5
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  supabase_flutter: ^2.15.4
  cupertino_icons: ^1.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/포레스트링_선생님_로고.png

  fonts:
    - family: ELAND
      fonts:
        - asset: assets/fonts/ELAND_초이스OTF-B.otf
          weight: 700
        - asset: assets/fonts/ELAND_초이스OTF-L.otf
          weight: 300
        - asset: assets/fonts/ELAND_초이스OTF-M.otf
          weight: 500
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500

flutter_native_splash:
  color: "#003717"
  image: 'assets/icon/선생님_아이콘.png'
  android: true
  ios: true
  fullscreen: true

  android_12:
    color: "#003717"
    image: 'assets/icon/선생님_아이콘.png'

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/선생님_아이콘.png"
  adaptive_icon_background: "#003717"
  adaptive_icon_foreground: "assets/icon/선생님_아이콘.png"
